CREATE OR REPLACE FUNCTION jeuLePlusPopulaire(
    CodeESRBCherche ESRB.CODE%TYPE
)
RETURN JEU.NOM%TYPE
IS
    CodeContenuPlusPopulaire CONTENU.IDCONTENU%TYPE;
    ContenuPlusPopulaire CONTENU%ROWTYPE;
    NomJeuPlusPopulaire JEU.NOM%TYPE;
BEGIN
    SELECT CONTENU_POSSEDE.IDCONTENU
    INTO CodeContenuPlusPopulaire
    FROM CONTENU_POSSEDE
    WHERE CONTENU_POSSEDE.IDCONTENU IN 
        (SELECT IDCONTENU FROM CONTENU WHERE TYPECONTENU = 'J' AND IDJEU IN (SELECT IDJEU FROM JEU WHERE CODEESRB = CodeESRBCherche))
    AND CONTENU_POSSEDE.NOJOUEUR IN
        (SELECT JOUEUR.NOJOUEUR FROM JOUEUR WHERE JOUEUR.ACTIF = 1)
    AND EXISTS(SELECT * FROM SUCCES_REALISE WHERE IDCONTENU = CONTENU_POSSEDE.IDCONTENU AND NOJOUEUR = CONTENU_POSSEDE.NOJOUEUR)
    AND ROWNUM = 1
    GROUP BY CONTENU_POSSEDE.IDCONTENU 
    ORDER BY COUNT(CONTENU_POSSEDE.IDCONTENU) DESC;
    
    SELECT * 
    INTO ContenuPlusPopulaire
    FROM CONTENU
    WHERE IDCONTENU = CodeContenuPlusPopulaire;
    
    SELECT NOM
    INTO NomJeuPlusPopulaire
    FROM JEU
    WHERE IDJEU = ContenuPlusPopulaire.IDJEU;
    
    RETURN NomJeuPlusPopulaire;
   
END;