CREATE OR REPLACE FUNCTION succesPlusRealise
RETURN SUCCES.TITRE%TYPE
IS
    IDSUCCESTROUVE SUCCES.IDSUCCES%TYPE;
    TITRESUCCESTROUVE SUCCES.TITRE%TYPE;
BEGIN
    SELECT IDSUCCES INTO IDSUCCESTROUVE FROM SUCCES_REALISE 
    WHERE ROWNUM = 1
    GROUP BY IDSUCCES 
    ORDER BY COUNT(IDSUCCES) DESC;
    
    SELECT SUCCES.TITRE INTO TITRESUCCESTROUVE FROM SUCCES 
    WHERE SUCCES.IDSUCCES = IDSUCCESTROUVE;
    
    RETURN TITRESUCCESTROUVE;
    
END;