CREATE OR REPLACE FUNCTION validerGenre(
    CODEGENRE GENRE.CODE%TYPE
)
RETURN GENRE.CODE%TYPE
IS
    CODEGENREPARENTTROUVE GENRE.CODE%TYPE;
BEGIN
    SELECT CODEGENREPARENT INTO CODEGENREPARENTTROUVE FROM GENRE WHERE CODE = CODEGENRE;
    
    IF(CODEGENREPARENTTROUVE = CODEGENRE) THEN --C'EST PAS UN SOUS-GENRE
        RETURN CODEGENRE;
    ELSIF(CODEGENREPARENTTROUVE != CODEGENRE) THEN --C'EST UN SOUS GENRE
        RETURN CODEGENREPARENTTROUVE;
    END IF;
END;