CREATE SEQUENCE CONTENU_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;
CREATE TRIGGER CONTENU_ID_TRG
    BEFORE INSERT
    ON CONTENU
    FOR EACH ROW
BEGIN
    SELECT CONTENU_SEQ.NEXTVAL
        INTO :NEW.IDCONTENU
        FROM DUAL;
END;
/

CREATE SEQUENCE JEU_SEQ;
CREATE TRIGGER JEU_ID_TRG
    BEFORE INSERT
    ON JEU
    FOR EACH ROW
BEGIN
    SELECT JEU_SEQ.NEXTVAL
        INTO :NEW.IDJEU
        FROM DUAL;
END;
/

CREATE SEQUENCE JOUEUR_SEQ;
CREATE TRIGGER JOUEUR_ID_TRG
    BEFORE INSERT
    ON JOUEUR
    FOR EACH ROW
BEGIN
    SELECT JOUEUR_SEQ.NEXTVAL
        INTO :NEW.NOJOUEUR
        FROM DUAL;
END;
/

CREATE SEQUENCE PERIODE_SEQ;
CREATE TRIGGER PERIODE_ID_TRG
    BEFORE INSERT
    ON PERIODE
    FOR EACH ROW
BEGIN
    SELECT PERIODE_SEQ.NEXTVAL
        INTO :NEW.IDPERIODE
        FROM DUAL;
END;
/

CREATE SEQUENCE SUCCES_SEQ;
CREATE TRIGGER SUCCES_ID_TRG
    BEFORE INSERT
    ON SUCCES
    FOR EACH ROW
BEGIN
    SELECT SUCCES_SEQ.NEXTVAL
        INTO :NEW.IDSUCCES
        FROM DUAL;
END;
/

CREATE SEQUENCE SUIVI_AMITIE_SEQ;
CREATE TRIGGER SUIVI_AMITIE_ID_TRG
    BEFORE INSERT
    ON SUIVI_AMITIE
    FOR EACH ROW
BEGIN
    SELECT SUIVI_AMITIE_SEQ.NEXTVAL
        INTO :NEW.IDSUIVI
        FROM DUAL;
END;
/

CREATE SEQUENCE SUIVI_RESEAU_SEQ;
CREATE TRIGGER SUIVI_RESEAU_ID_TRG
    BEFORE INSERT
    ON SUIVI_RESEAU
    FOR EACH ROW
BEGIN
    SELECT SUIVI_RESEAU_SEQ.NEXTVAL
        INTO :NEW.IDSUIVI
        FROM DUAL;
END;
/


