CREATE OR REPLACE TRIGGER Suivi_Ami_TRG
AFTER UPDATE OR INSERT OR DELETE
ON AMI
FOR EACH ROW

DECLARE 
    currentMoment timestamp;

BEGIN
    SELECT SYSTIMESTAMP into currentMoment FROM DUAL;

    if INSERTING or UPDATING
    then
        insert into SUIVI_AMITIE (DATESUIVI, CODESTATUT, NOJOUEURINVITANT, NOJOUEURINVITE)
        values (currentMoment, :NEW.CODESTATUT, :NEW.NOJOUEURINVITANT, :NEW.NOJOUEURINVITE);
        
    elsif DELETING
    then
        insert into SUIVI_AMITIE (DATESUIVI, CODESTATUT, NOJOUEURINVITANT, NOJOUEURINVITE)
        values (currentMoment, :OLD.CODESTATUT, :OLD.NOJOUEURINVITANT, :OLD.NOJOUEURINVITE);

    end if;

END;
/