CREATE OR REPLACE TRIGGER Suivi_Abonnement_Reseau_TRG
AFTER DELETE OR INSERT 
ON ABONNEMENT_RESEAU
FOR EACH ROW

DECLARE 
    currentDate DATE;
    currentAction SUIVI_RESEAU.ACTION%TYPE;
BEGIN
    SELECT SYSDATE into currentDate FROM DUAL;
    
    IF DELETING THEN
        INSERT INTO SUIVI_RESEAU (CODERESEAU, DATESUIVI, ACTION, NOJOUEUR) VALUES (:OLD.CODERESEAU, currentDate, 'DSA', :OLD.NOJOUEUR);
        
    ELSIF INSERTING THEN
        INSERT INTO SUIVI_RESEAU (CODERESEAU, DATESUIVI, ACTION, NOJOUEUR) VALUES (:NEW.CODERESEAU, currentDate, 'ABO', :NEW.NOJOUEUR);
        
    END IF;
    
END;    
/