CREATE OR REPLACE PROCEDURE ajusterPromotion(
    CodeForfait OUT FORFAIT.CODE%TYPE,
    NewPrice OUT PERIODE.PRIX%TYPE
    )
IS
    CodeReseauPlusPopulaire ABONNEMENT_RESEAU.CODERESEAU%TYPE;
BEGIN
    NomForfait := Nom;
    
    SELECT * INTO CodeReseauPlusPopulaire FROM (SELECT CODERESEAU FROM ABONNEMENT_RESEAU GROUP BY CODERESEAU ORDER BY COUNT(CODERESEAU) DESC) WHERE rownum = 1;
    

    
    
    
END;
/
    
