CREATE OR REPLACE PROCEDURE ajusterPromotion(
    CodeForfait OUT FORFAIT.CODE%TYPE,
    NewPrice OUT PERIODE.PRIX%TYPE
    )
IS
    CodeReseauPlusPopulaire ABONNEMENT_RESEAU.CODERESEAU%TYPE;
    CodeForfaitPlusCher FORFAIT.CODE%TYPE;
BEGIN
    
    SELECT * INTO CodeReseauPlusPopulaire FROM (SELECT CODERESEAU FROM ABONNEMENT_RESEAU GROUP BY CODERESEAU ORDER BY COUNT(CODERESEAU) DESC) WHERE rownum = 1;
    
    SELECT * INTO CodeForfait FROM (SELECT PERIODE.CODEFORFAIT FROM JOUEUR JOIN ABONNEMENT_RESEAU ON JOUEUR.NOJOUEUR = ABONNEMENT_RESEAU.NOJOUEUR
    JOIN PERIODE_FORFAIT_JOUEUR ON PERIODE_FORFAIT_JOUEUR.NOJOUEUR = JOUEUR.NOJOUEUR
    JOIN PERIODE ON PERIODE.IDPERIODE = PERIODE_FORFAIT_JOUEUR.IDPERIODE
    WHERE ABONNEMENT_RESEAU.CODERESEAU = 'FRANCO'
    GROUP BY PERIODE.CODEFORFAIT
    ORDER BY COUNT(PERIODE.CODEFORFAIT) DESC)
    WHERE ROWNUM = 1;
    
    SELECT * INTO CodeForfaitPlusCher FROM (SELECT CodeForfait FROM PERIODE GROUP BY CodeForfait ORDER BY MAX(PRIX) DESC) WHERE ROWNUM = 1;
    
    IF (CodeForfait != CodeForfaitPlusCher) THEN
        UPDATE PERIODE SET PRIX = PRIX*1.1 WHERE CODEFORFAIT = CodeForfait; 
    END IF;
    
    SELECT PERIODE.PRIX INTO NewPrice FROM PERIODE WHERE PERIODE.CODEFORFAIT = CodeForfait AND ROWNUM = 1;
    
END;
/
    
