CREATE OR REPLACE PROCEDURE ajusterPromotion(
    CodeForfait OUT FORFAIT.CODE%TYPE,
    NewPrice OUT PERIODE.PRIX%TYPE
    )
IS
    IDForfaitPlusPopulaire PERIODE.IDPERIODE%TYPE;
    CodeReseauPlusPopulaire ABONNEMENT_RESEAU.CODERESEAU%TYPE;
    CodeForfaitPlusCher FORFAIT.CODE%TYPE;
BEGIN
    
    SELECT * INTO CodeReseauPlusPopulaire FROM (SELECT CODERESEAU FROM ABONNEMENT_RESEAU GROUP BY CODERESEAU ORDER BY COUNT(CODERESEAU) DESC) WHERE ROWNUM = 1;
    
    SELECT * INTO IDForfaitPlusPopulaire FROM (SELECT PERIODE.IDPERIODE FROM JOUEUR 
    JOIN ABONNEMENT_RESEAU ON JOUEUR.NOJOUEUR = ABONNEMENT_RESEAU.NOJOUEUR
    JOIN PERIODE_FORFAIT_JOUEUR ON PERIODE_FORFAIT_JOUEUR.NOJOUEUR = JOUEUR.NOJOUEUR
    JOIN PERIODE ON PERIODE.IDPERIODE = PERIODE_FORFAIT_JOUEUR.IDPERIODE
    WHERE ABONNEMENT_RESEAU.CODERESEAU = CodeReseauPlusPopulaire
    GROUP BY PERIODE.IDPERIODE
    ORDER BY COUNT(PERIODE.IDPERIODE) DESC)
    WHERE ROWNUM = 1;
    
    SELECT * INTO CodeForfaitPlusCher FROM (SELECT IDPERIODE FROM PERIODE GROUP BY IDPERIODE ORDER BY MAX(PRIX) DESC) WHERE ROWNUM = 1;
    
    IF (IDForfaitPlusPopulaire != CodeForfaitPlusCher) THEN
        UPDATE PERIODE SET PRIX = PRIX*1.1 WHERE IDPERIODE = IDForfaitPlusPopulaire; 
    END IF;
    
    SELECT PERIODE.PRIX, PERIODE.CODEFORFAIT INTO NewPrice, CodeForfait FROM PERIODE WHERE PERIODE.IDPERIODE = IDForfaitPlusPopulaire AND ROWNUM = 1;

    
END;
/
    
