CREATE OR REPLACE PROCEDURE ajoutForfait(
    CodeForfait IN FORFAIT.CODE%TYPE,
    PlayerCount OUT NUMBER
    )
IS
    
    
    rec_PERIODE_FORFAIT_JOUEUR PERIODE_FORFAIT_JOUEUR%ROWTYPE;
    Today DATE;
    
    CURSOR cur_PERIODE_FORFAIT_JOUEUR IS
    SELECT * FROM PERIODE_FORFAIT_JOUEUR WHERE
    IDPERIODE IN (SELECT PERIODE.IDPERIODE FROM PERIODE WHERE CODEFORFAIT = CodeForfait);
BEGIN
    SELECT SYSDATE INTO Today FROM DUAL;

    FETCH cur_PERIODE_FORFAIT_JOUEUR INTO rec_PERIODE_FORFAIT_JOUEUR;
    WHILE cur_PERIODE_FORFAIT_JOUEUR%FOUND LOOP
        IF (rec_PERIODE_FORFAIT_JOUEUR.DATEACHAT < add_months(Today, 12)) 
        THEN
            UPDATE PERIODE_FORFAIT_JOUEUR SET DATEACHAT = add_months(DATEACHAT, 2)
            WHERE IDPERIODE = rec_PERIODE_FORFAIT_JOUEUR.IDPERIODE;
            PlayerCount := PlayerCount + 1;
        END IF;
        FETCH cur_PERIODE_FORFAIT_JOUEUR INTO rec_PERIODE_FORFAIT_JOUEUR;
    END LOOP;
    
    
    CLOSE cur_PERIODE_FORFAIT_JOUEUR;
    
END;
/